# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f731ec9eb809289d74980dfb9debb7ee53cb1964d1e78c74ecdb0ced8f3a8a597625ab863a34032652b4d154e5f09936dd8cd39b1ab48a7b343615c48f13412d

test:
  secret_key_base: 11080420f49fccd249d950d83037c9773fa256fc04f234cb12038689cf0dfab0e5d41e663c5e10e9c6829e72227fc91d819d3af64d8bc1bc839ff84a9e37bf32

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
